version: '3.2'

services:

#-------------------------------------------
# CONSUL
#-------------------------------------------
  consul:
    restart: always
    # image: bhuisgen/alpine-consul
    build:
      context: ./docker/alpine-consul
    ports:
      - "8500:8500"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

#-------------------------------------------
# ADMINER
#-------------------------------------------
  adminer:
    restart: always
    build:
      context: ./docker/adminer/${ADMINER_VERSION}
    ports:
      - "${ADMINER_PORT}:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SESSION_ADMINER}:/sessions                       # volume for data
    networks:
      - backend

#-------------------------------------------
# PHP 5.x
#-------------------------------------------
  php5:
    restart: always
    depends_on:
      - consul
    build:
      context: ./docker/alpine-php5/${PHP5_VERSION}
    ports:
      - "${PHP5_PORT}:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_AGENT=consul                   # consul agent hostname/IP
      - CONSUL_SERVICENAME=php5               # consul service name
      - CONSUL_SERVICETAGS=dev                # consul service tag
      - CONSUL_SERVICEPORT=9000               # consul service port
      - CONSUL_CHECKTYPE=tcp                  # consul health check type
      - PHP_MANAGER=static                    # process manager mode (static/dynamic/ondemand)
      - PHP_MAXCHILDREN=10                    # maximum children (static/ondemand)
      - PHP_STATUSPATH=/status                # path of status page
      - PHP_PINGPATH=/ping                    # path of ping page
      - PHP_ACCESSFORMAT="%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"    # access format
      - PHP_REQUESTSLOWLOGTIMEOUT=10          # timeout for logging slow requests
      - PHP_REQUESTTERMINATETIMEOUT=30        # timeout for killing running processes
    networks:
      - backend

#-------------------------------------------
# PHP 7.x
#-------------------------------------------
  php7:
    restart: always
    depends_on:
      - consul
    build:
      context: ./docker/alpine-php7/${PHP7_VERSION}
    ports:
      - "${PHP7_PORT}:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_AGENT=consul                   # consul agent hostname/IP
      - CONSUL_SERVICENAME=php7               # consul service name
      - CONSUL_SERVICETAGS=dev                # consul service tag
      - CONSUL_SERVICEPORT=9000               # consul service port
      - CONSUL_CHECKTYPE=tcp                  # consul health check type
      - PHP_MANAGER=static                    # process manager mode (static/dynamic/ondemand)
      - PHP_MAXCHILDREN=10                    # maximum children (static/ondemand)
      - PHP_STATUSPATH=/status                # path of status page
      - PHP_PINGPATH=/ping                    # path of ping page
      - PHP_ACCESSFORMAT="%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %C%%"    # access format
      - PHP_REQUESTSLOWLOGTIMEOUT=10          # timeout for logging slow requests
      - PHP_REQUESTTERMINATETIMEOUT=30        # timeout for killing running processes
    networks:
      - backend


#-------------------------------------------
# PHPMYADMIN
#-------------------------------------------
  phpmyadmin:
    restart: always
    depends_on:
      - consul
    build:
      context: ./docker/alpine-phpmyadmin/${PHPMYADMIN_VERSION}
    entrypoint: /bin/sh
    ports:
      - "${PHPMYADMIN_PORT}:8082"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

#-------------------------------------------
# RUBY
#-------------------------------------------
  ruby:
    restart: always
    depends_on:
      - consul
    build:
      context: ./docker/alpine-ruby
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_AGENT=consul
    networks:
      - backend

#-------------------------------------------------------------------
# NETWORK SETUP
#-------------------------------------------------------------------
networks:
  backend:
    driver: "bridge"

#-------------------------------------------------------------------
# VOLUME SETUP
#-------------------------------------------------------------------
volumes:
  adminer:
    driver: "local"
  php5:
    driver: "local"
  php7:
    driver: "local"
  phpmyadmin:
    driver: "local"
  ruby:
    driver: "local"