version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    java:
        depends_on:
            - consul
        image: bhuisgen/alpine-java
        network_mode: host
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_AGENT=consul                  # consul agent hostname/IP
            #- CONSUL_PORT=8500                    # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/       # consul key prefix path

