version: '3.2'

services:
    consul:
        image: bhuisgen/alpine-consul
        ports:
            - "8500:8500"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_OPTIONS=-server -bootstrap-expect 1 -client 0.0.0.0 -ui    # minimal server options

    spark-master:
        depends_on:
            - consul
        image: bhuisgen/alpine-spark
        expose:
          - 7001
          - 7002
          - 7003
          - 7004
          - 7005
          - 7006
          - 7077
          - 6066
        ports:
          - "4040:4040"
          - "6066:6066"
          - "7077:7077"
          - "8080:8080"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_AGENT=consul                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/            # consul key prefix path
            - CONSUL_SERVICENAME=spark-master           # consul service name
            - CONSUL_SERVICETAGS=dev                    # consul service tag
            - CONSUL_SERVICEPORT=8080                   # consul service port
            - CONSUL_CHECKTYPE=tcp                      # consul health check type

    spark-worker1:
        depends_on:
            - consul
        image: bhuisgen/alpine-spark
        expose:
          - 7012
          - 7013
          - 7014
          - 7015
          - 7016
          - 8881
        ports:
          - "8081:8081"
        volumes:
            - /etc/localtime:/etc/localtime:ro
        environment:
            - CONSUL_AGENT=consul                       # consul agent hostname/IP
            #- CONSUL_PORT=8500                         # consul agent port
            #- CONSUL_KEYPREFIX=path/prefix/            # consul key prefix path
            - CONSUL_SERVICENAME=spark-worker1          # consul service name
            - CONSUL_SERVICETAGS=dev                    # consul service tag
            - CONSUL_SERVICEPORT=8081                   # consul service port
            - CONSUL_CHECKTYPE=tcp                      # consul health check type
            - SPARK_MASTERURL=spark://spark-master:7077 # spark master URL
